consai2r2_teleop:
  ros__parameters:
    button_shutdown_1       : 8
    button_shutdown_2       : 9

    button_move_enable      : 4
    axis_vel_surge          : 1
    axis_vel_sway           : 0
    axis_vel_angular        : 2

    # button_kick_enable      : 5
    # button_kick_straight    : 0
    # button_kick_chip        : 3
    # axis_kick_power         : 5

    # button_dribble_enable   : 7
    # axis_dribble_power      : 5

    # button_id_enable        : 9
    # axis_id_change          : 5

    # button_color_enable     : 8
    # axis_color_change       : 5
